---
# Resolver settings
  - name: Add options in /etc/resolv.conf
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      create: yes
      state: present
      line: 'options timeout:3 attempts:1 rotate'
      regexp: '^options'
  - name: Add comment for "domain" directive
    when: DNS_searchname != None
    ansible.builtin.replace:
      dest: /etc/resolv.conf
      replace: '#\1'
      regexp: '(^domain.*$)'
  - name: Add search in /etc/resolv.conf
    when: DNS_searchname != None
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      state: present
      line: 'search {{ DNS_searchname }}'
      regexp: '^search'
  - name: Remove nameserver line from /etc/resolv/conf
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      state: absent
      regexp: '^nameserver(.*)'
  - name: Add NS1 in /etc/resolv.conf
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      state: present
      line: 'nameserver {{ DNS_IP1 }}'
      regexp: '^nameserver {{ DNS_IP1 }}'
  - name: Add NS2 in /etc/resolv.conf
    when: DNS_IP2 != None
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      state: present
      line: 'nameserver {{ DNS_IP2 }}'
      regexp: '^nameserver {{ DNS_IP2 }}'
  - name: Add NS3 in /etc/resolv.conf
    when: DNS_IP3 != None
    ansible.builtin.lineinfile:
      path: /etc/resolv.conf
      state: present
      line: 'nameserver {{ DNS_IP3 }}'
      regexp: '^nameserver {{ DNS_IP3 }}'
