---
  - name: Copy crt files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/share/ca-certificates/
    with_fileglob: "files/usr/local/share/ca-certificates/*.crt"
    notify:
    - run update-ca-certificates
