---
  - name: Add comment for default cdrom repo
    ansible.builtin.replace:
      dest: /etc/apt/sources.list
      replace: '#\1'
      regexp: '(^deb\scdrom:.*$)'
  - name: Add local infra repo
    when: AstraSE_localrepo != None
    template:
      src: etc/apt/sources.list.d/infra_repo.j2
      dest: /etc/apt/sources.list.d/infra_repo.list
      owner: root
      group: root
      mode: 0644
    become: yes
