---
  - name: Install exim4, if host is configured in variable "exim_smarthost"
    when: exim_smarthost != None
    ansible.builtin.apt:
      name: exim4
      state: latest
      update_cache: no
  - name: Configuring exim4 server, if host is configured in variable "exim_smarthost"
    when: exim_smarthost != None
    template:
      src: etc/exim4/update-exim4.conf.conf.j2
      dest: /etc/exim4/update-exim4.conf.conf
      owner: root
      group: root
      mode: 0644
    become: yes
    notify:
    - restart exim4
  - name: Send test email
    when: exim_smarthost != None
    ansible.builtin.shell: echo -e "{{ ansible_hostname }}\n{{ ansible_default_ipv4.address }}" | mail -s "Test email notyfication from {{ ansible_hostname }}" {{ admins_email }}

