---
  - name: Remove Astra default "server" directive from /etc/chrony/chrony.conf
    ansible.builtin.lineinfile:
      path: /etc/chrony/chrony.conf
      state: absent
      regexp: '^server.*$'
    notify:
    - restart chrony
  - name: Remove Astra default "pool" directive from /etc/chrony/chrony.conf
    ansible.builtin.lineinfile:
      path: /etc/chrony/chrony.conf
      state: absent
      regexp: '^pool.*$'
    notify:
    - restart chrony
  - name: Add NTP in /etc/chrony/chrony.conf
    when: NTP_IP != None
    ansible.builtin.lineinfile:
      path: /etc/chrony/chrony.conf
      state: present
      line: 'server {{ item }} iburst'
    with_items:
    - "{{ NTP_IP }}"
    notify:
    - restart chrony
