---
  - name: Copy sshd banner file
    ansible.builtin.copy:
      src: files/etc/ssh/ssh_banner
      dest: /etc/ssh/
      owner: root
      group: root
      mode: '0644'
  - name: Add banner directive in sshd_config
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      line: 'Banner /etc/ssh/ssh_banner'
      regexp: '^Banner\s'
      insertbefore: '^# no default banner path'
    become: yes
    notify:
    - restart sshd.service
